# Mean Normalization

In machine learning we use large amounts of data to train our models. Some machine learning algorithms may require that the data is *normalized* in order to work correctly. The idea of normalization, also known as *feature scaling*, is to ensure that all the data is on a similar scale, *i.e.* that all the data takes on a similar range of values. For example, we might have a dataset that has values between 0 and 5,000. By normalizing the data we can make the range of values be between 0 and 1.

In this lab, you will be performing a different kind of feature scaling known as *mean normalization*. Mean normalization will scale the data, but instead of making the values be between 0 and 1, it will distribute the values evenly in some small interval around zero. For example, if we have a dataset that has values between 0 and 5,000, after mean normalization the range of values will be distributed in some small range around 0, for example between -3 to 3. Because the range of values are distributed evenly around zero, this guarantees that the average (mean) of all elements will be zero. Therefore, when you perform *mean normalization* your data will not only be scaled but it will also have an average of zero. 

# To Do:

You will start by importing NumPy and creating a rank 2 ndarray of random integers between 0 and 5,000 (inclusive) with 1000 rows and 20 columns. This array will simulate a dataset with a wide range of values. Fill in the code below

In [3]:
# import NumPy into Python

import numpy as np

# Create a 1000 x 20 ndarray with random integers in the half-open interval [0, 5001).
X = np.random.randint(0, 5001, (1000, 20))

# print the shape of X
print(X)

[[2555  969  511 ... 1630  993 4410]
 [3772 1646 1228 ... 3941 2441 1367]
 [ 431 3111 3557 ...  650 1894 4668]
 ...
 [3923 4356  756 ... 4671 2544  950]
 [1832 1330 4148 ... 2152 1909 1834]
 [1096  652 3166 ... 4477 2417 3290]]


Now that you created the array we will mean normalize it. We will perform mean normalization using the following equation:

$\mbox{Norm_Col}_i = \frac{\mbox{Col}_i - \mu_i}{\sigma_i}$

where $\mbox{Col}_i$ is the $i$th column of $X$, $\mu_i$ is average of the values in the $i$th column of $X$, and $\sigma_i$ is the standard deviation of the values in the $i$th column of $X$. In other words, mean normalization is performed by subtracting from each column of $X$ the average of its values, and then by dividing by the standard deviation of its values. In the space below, you will first calculate the average and standard deviation of each column of $X$. 

In [14]:
# Average of the values in each column of X
ave_cols = np.mean(X, axis=0)
print(ave_cols)

# Standard Deviation of the values in each column of X
std_cols = np.std(X, axis=0)
print(std_cols)

[2491.401 2451.674 2459.696 2508.986 2433.259 2476.929 2472.456 2500.675
 2499.219 2466.571 2426.699 2522.725 2443.585 2536.959 2462.973 2477.903
 2536.609 2521.644 2511.902 2505.526]
[1417.35375549 1432.083811   1457.83851423 1461.34572084 1413.85778348
 1477.42232552 1446.49475286 1457.63939415 1448.11133724 1429.59099359
 1431.89508848 1464.71875641 1464.69006646 1426.73151199 1455.10738307
 1408.76396873 1438.06444366 1492.89279028 1486.70558161 1438.26763758]


If you have done the above calculations correctly, then `ave_cols` and `std_cols`, should both be vectors with shape `(20,)` since $X$ has 20 columns. You can verify this by filling the code below:

In [9]:
# Print the shape of ave_cols
print(ave_cols.shape)

# Print the shape of std_cols
print(std_cols.shape)

(20,)
(20,)


You can now take advantage of Broadcasting to calculate the mean normalized version of $X$ in just one line of code using the equation above. Fill in the code below

In [10]:
# Mean normalize X
X_norm = (X - ave_cols)/std_cols
print(X_norm)

[[ 0.04487165 -1.03532628 -1.33670223 ... -0.59725923 -1.02165622
   1.32414437]
 [ 0.90351403 -0.56258858 -0.84487821 ...  0.95074208 -0.04769068
  -0.79159537]
 [-1.45369566  0.46039624  0.75269242 ... -1.25370289 -0.41561827
   1.50352684]
 ...
 [ 1.01005059  1.32975877 -1.16864521 ...  1.43972562  0.02159002
  -1.0815275 ]
 [-0.46523389 -0.78324606  1.15808712 ... -0.24760251 -0.40552885
  -0.46689919]
 [-0.98451145 -1.25668204  0.48448713 ...  1.30977657 -0.06383376
   0.54542978]]


If you have performed the mean normalization correctly, then the average of all the elements in $X_{\tiny{\mbox{norm}}}$ should be close to zero, and they should be evenly distributed in some small interval around zero. You can verify this by filing the code below:

In [13]:
# Print the average of all the values of X_norm

print(X_norm.mean())

# Print the average of the minimum value in each column of X_norm
print(X_norm.min(axis=0).mean())

# Print the average of the maximum value in each column of X_norm
print(X_norm.max(axis=0).mean())

3.055333763768431e-17
-1.7143953264367569
1.7352531121237962


You should note that since $X$ was created using random integers, the above values will vary. 

# Data Separation

After the data has been mean normalized, it is customary in machine learnig to split our dataset into three sets:

1. A Training Set
2. A Cross Validation Set
3. A Test Set

The dataset is usually divided such that the Training Set contains 60% of the data, the Cross Validation Set contains 20% of the data, and the Test Set contains 20% of the data. 

In this part of the lab you will separate `X_norm` into a Training Set, Cross Validation Set, and a Test Set. Each data set will contain rows of `X_norm` chosen at random, making sure that we don't pick the same row twice. This will guarantee that all the rows of `X_norm` are chosen and randomly distributed among the three new sets.

You will start by creating a rank 1 ndarray that contains a random permutation of the row indices of `X_norm`. You can do this by using the `np.random.permutation()` function. The `np.random.permutation(N)` function creates a random permutation of integers from 0 to `N - 1`. Let's see an example:

In [15]:
# We create a random permutation of integers 0 to 4
np.random.permutation(5)


array([1, 0, 4, 3, 2])

# To Do

In the space below create a rank 1 ndarray that contains a random permutation of the row indices of `X_norm`. You can do this in one line of code by extracting the number of rows of `X_norm` using the `shape` attribute and then passing it to the  `np.random.permutation()` function. Remember the `shape` attribute returns a tuple with two numbers in the form `(rows,columns)`.

In [35]:
# Create a rank 1 ndarray that contains a random permutation of the row indices of `X_norm`
row, col = X_norm.shape
row_indices = np.random.permutation(row)
print(row_indices.shape)

(1000,)


Now you can create the three datasets using the `row_indices` ndarray to select the rows that will go into each dataset. Rememeber that the Training Set contains 60% of the data, the Cross Validation Set contains 20% of the data, and the Test Set contains 20% of the data. Each set requires just one line of code to create. Fill in the code below

In [36]:
# Make any necessary calculations.
# You can save your calculations into variables to use later.


# Create a Training Set
X_train = X_norm[row_indices[0:600]]


# Create a Cross Validation Set
X_crossVal =X_norm[row_indices[600:800]]

# Create a Test Set
X_test = X_norm[row_indices[800:1000]]

In [37]:
# Print the shape of X_train

print(X_train.shape)
# Print the shape of X_crossVal
print(X_crossVal.shape)

# Print the shape of X_test
print(X_test.shape)

(600, 20)
(200, 20)
(200, 20)
